import type { Metadata } from "next";
import "./globals.scss";
import { Navbar } from "@/widgets/navbar";
import { SideModal } from "@/features/side-modal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <SideModal 
          
        />
      </body>
    </html>
  );
}
